# Clock constraints
create_clock -name "clock" -period "2.1" [get_ports {clock}]
set_false_path -from [get_ports resetn]

# Pin constraints
set_property PACKAGE_PIN V20 [get_ports clock]
set_property PACKAGE_PIN V14 [get_ports porta[0]]
set_property PACKAGE_PIN U15 [get_ports porta[1]]
set_property PACKAGE_PIN T15 [get_ports porta[2]]
set_property PACKAGE_PIN W15 [get_ports porta[3]]
set_property PACKAGE_PIN V15 [get_ports porta[4]]
set_property PACKAGE_PIN Y14 [get_ports porta[5]]
set_property PACKAGE_PIN W14 [get_ports porta[6]]
set_property PACKAGE_PIN Y16 [get_ports porta[7]]
set_property PACKAGE_PIN W16 [get_ports portb[0]]
set_property PACKAGE_PIN T16 [get_ports portb[1]]
set_property PACKAGE_PIN R16 [get_ports portb[2]]
set_property PACKAGE_PIN V17 [get_ports portb[3]]
set_property PACKAGE_PIN U16 [get_ports portb[4]]
set_property PACKAGE_PIN AA15 [get_ports portb[5]]
set_property PACKAGE_PIN AA14 [get_ports portb[6]]
set_property PACKAGE_PIN AB17 [get_ports portb[7]]
set_property PACKAGE_PIN AA16 [get_ports portc[0]]
set_property PACKAGE_PIN AB16 [get_ports portc[1]]
set_property PACKAGE_PIN AB15 [get_ports portc[2]]
set_property PACKAGE_PIN AB18 [get_ports portc[3]]
set_property PACKAGE_PIN AA18 [get_ports portc[4]]
set_property PACKAGE_PIN Y17 [get_ports portc[5]]
set_property PACKAGE_PIN W17 [get_ports portc[6]]
set_property PACKAGE_PIN Y19 [get_ports portc[7]]
set_property PACKAGE_PIN Y18 [get_ports resetn]
set_property IOSTANDARD LVCMOS18 [all_inputs]
set_property IOSTANDARD LVCMOS18 [all_outputs]
