# 
# Synthesis run script generated by Vivado
# 
read_verilog {
  alu.v
  data_mux.v
  ins_decode.v
  ins_rom.v
  io.v
  prgm_cntr.v
  reg_file.v
  spcl_regs.v
  eight_bit_uc.v
}
read_xdc eight_bit_uc.sdc

synth_design -top eight_bit_uc -part xc7k70tfbg484-2

write_checkpoint -force -noxdef eight_bit_uc_synth.dcp

set rc [catch {
  opt_design 
  write_checkpoint -force eight_bit_uc_opt.dcp
} RESULT]
if {$rc} {
  return -code error $RESULT
}

set rc [catch {
  place_design 
  write_checkpoint -force eight_bit_uc_placed.dcp
} RESULT]
if {$rc} {
  return -code error $RESULT
}

set rc [catch {
  route_design 
  write_checkpoint -force eight_bit_uc_routed.dcp
} RESULT]
if {$rc} {
  write_checkpoint -force eight_bit_uc_routed_error.dcp
  return -code error $RESULT
}